### ISSUE TITLE
Implement density

### ISSUE THREAD

**Issue by ddamato** [damato-design/system#20]
Need an appropriate method of using expected depth to influence the size of text and space.

**Comment by ddamato** [comment]
`sizes` is used to help compute the final `text` and `space` tokens. This eventually creates a repeated set of selectors to update the size.

```css
[data-mode="system:denser"] {
  --level: calc(var(--sizes) - 0);
}

[data-mode="system:denser"] [data-mode="system:denser"] {
  --level: calc(var(--sizes) - 1);
}
```

The number of `sizes` is _not_ dependent on the incoming mode but on the page composition. In other words, each page predetermined the number of sizes expected to be used. If not set, density changes are not used, and all `text` and `space` results as `--level: 0` (`--size: 1`).

This means a script must be included that appends necessary styles to the head that generates the accompanying CSS; accepting a `sizes` setting.
